ClienteAPP/ClienteAPP/Models/PedidoVisita.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ClienteAPP.Models
{
    public class PedidoVisita
    {
        [HiddenInput(DisplayValue = false)]
        public int PedidoVisitaId { get; set; }

        [Required, HiddenInput(DisplayValue = false), DisplayName("ID do cliente")]
        public string ClienteId { get; set; }

        [Required, HiddenInput(DisplayValue = false), DisplayName("ID do mediador")]
        public string MediadorId { get; set; }

        [Required, HiddenInput(DisplayValue = false), DisplayName("ID do imóvel")]
        public int ImovelId { get; set; }

        [Required, DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Data { get; set; }

        [Required, DataType(DataType.Time), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm}")]
        public DateTime Hora { get; set; }

        [DisplayName("Estado do pedido de visita")]
        public string Estado { get; set; }
    }
}

ClienteAPP/ClienteAPP/Controllers/PedidoVisitaController.cs
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Collections.Generic;
using ClienteAPP.Models;
using System.Net;
using System.Linq;
using System;
using Newtonsoft.Json;
using ClienteAPP.Helpers;
using System.Net.Http;

namespace ClienteAPP.Controllers
{
    public class PedidoVisitaController : Controller
    {
        // GET: PedidoVisita
        public async Task<ActionResult> Index()
        {
            if (WebApiHttpClient.getToken() == null)
                return RedirectToAction("UnAuthenticated", "Home");

            IEnumerable<PedidoVisita> visitas = await getAll();
            if (visitas != null)
            {
                Imovel_Venda_Permuta_AluguerController ImovelCtrl = new Imovel_Venda_Permuta_AluguerController();
                List<Imovel_Venda_Permuta_Aluguer> imoveis = new List<Imovel_Venda_Permuta_Aluguer>();
                foreach (PedidoVisita visita in visitas)
                    imoveis.Add(await ImovelCtrl.get(visita.ImovelId));

                ViewBag.visitas = visitas;
                ViewBag.imoveis = imoveis;
            }
            else
            {
                ViewBag.visitas = new List<PedidoVisita>();
                ViewBag.imoveis = new List<Imovel_Venda_Permuta_Aluguer>();
            }
            return View();
        }

        public async Task<IEnumerable<PedidoVisita>> getAll()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/PedidoVisita/");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var visitas = JsonConvert.DeserializeObject<IEnumerable<PedidoVisita>>(content);
                return visitas;
            }
            else
                return null;
        }

        // GET: PedidoVisita/Create/id
        public async Task<ActionResult> Create(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Imovel_Venda_Permuta_AluguerController ImovelCtrl = new Imovel_Venda_Permuta_AluguerController();
            Anuncio_VendaController AnuncioVendaCtrl = new Anuncio_VendaController();
            IEnumerable<Anuncio_Venda> AnuncioVendaList = await AnuncioVendaCtrl.getAll();
            if (AnuncioVendaList != null)
                foreach (Anuncio_Venda anuncio in AnuncioVendaList)
                    if (anuncio.ID == id)
                    {
                        Imovel_Venda_Permuta_Aluguer imovel = await ImovelCtrl.get(anuncio.ImovelID);
                        ViewBag.imovel = imovel;
                        ViewBag.anuncio = anuncio;
                        PedidoVisita visita = new PedidoVisita { ImovelId = imovel.ID, MediadorId = anuncio.MediadorID };
                        return View(visita);
                    }

            Anuncio_AluguerController AnuncioAluguerCtrl = new Anuncio_AluguerController();
            IEnumerable<Anuncio_Aluguer> AnuncioAluguerList = await AnuncioAluguerCtrl.getAll();
            if (AnuncioAluguerList != null)
                foreach (Anuncio_Aluguer anuncio in AnuncioAluguerList)
                    if (anuncio.ID == id)
                    {
                        Imovel_Venda_Permuta_Aluguer imovel = await ImovelCtrl.get(anuncio.ImovelID);
                        ViewBag.imovel = imovel;
                        ViewBag.anuncio = anuncio;
                        PedidoVisita visita = new PedidoVisita { ImovelId = imovel.ID, MediadorId = anuncio.MediadorID };
                        return View(visita);
                    }

            Anuncio_PermutaController AnuncioPermutaCtrl = new Anuncio_PermutaController();
            IEnumerable<Anuncio_Permuta> AnuncioPermutaList = await AnuncioPermutaCtrl.getAll();
            if (AnuncioPermutaList != null)
                foreach (Anuncio_Permuta anuncio in AnuncioPermutaList)
                    if (anuncio.ID == id)
                    {
                        Imovel_Venda_Permuta_Aluguer imovel = await ImovelCtrl.get(anuncio.ImovelID);
                        ViewBag.imovel = imovel;
                        ViewBag.anuncio = anuncio;
                        PedidoVisita visita = new PedidoVisita { ImovelId = imovel.ID, MediadorId = anuncio.MediadorID };
                        return View(visita);
                    }

            return RedirectToAction("Erro", "Home");
        }

        // POST: PedidoVisita/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "MediadorId, ImovelId, Hora, Data")] PedidoVisita visita)
        {
            try
            {
                Imovel_Venda_Permuta_AluguerController ImovelCtrl = new Imovel_Venda_Permuta_AluguerController();
                Imovel_Venda_Permuta_Aluguer imovel = await ImovelCtrl.get(visita.ImovelId);
                string diaSemana = visita.Data.DayOfWeek.ToString();
                List<string> diasDaSemana = imovel.DiasSemana.Split(';').ToList();
                foreach (string dia in diasDaSemana)
                    if (dia == diaSemana && imovel.HoraAbertura <= Convert.ToInt32(visita.Hora.Hour.ToString())
                        && imovel.HoraFecho >= Convert.ToInt32(visita.Hora.Hour.ToString()))
                    {
                        visita.Estado = "Por aprovar";
                        var client = WebApiHttpClient.GetClient();
                        string visitaJSON = JsonConvert.SerializeObject(visita);
                        HttpContent content = new StringContent(visitaJSON,
                        System.Text.Encoding.Unicode, "application/json");
                        var response = await client.PostAsync("api/PedidoVisita/", content);

                        if (response.IsSuccessStatusCode)
                            return RedirectToAction("Index", "Anuncios");
                        else
                            return RedirectToAction("Erro", "Home");
                    }
                return Content("ERRO: O imóvel não se encontra disponivel na data ou hora escolhida.");
            }
            catch
            {
                return RedirectToAction("Erro", "Home");
            }
        }

        // GET: PedidoVisita/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/PedidoVisita/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var visita = JsonConvert.DeserializeObject<PedidoVisita>(content);
                if (visita == null)
                    return HttpNotFound();

                Imovel_Venda_Permuta_AluguerController ImovelCtrl = new Imovel_Venda_Permuta_AluguerController();
                Imovel_Venda_Permuta_Aluguer imovel = await ImovelCtrl.get(visita.ImovelId);
                ViewBag.imovel = imovel;
                return View(visita);
            }
            return RedirectToAction("UnAuthenticated", "Home");
        }

        // POST: PedidoVisita/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PedidoVisitaId, ClienteId, MediadorId, ImovelId, Data, Hora, Estado")] PedidoVisita visita)
        {
            try
            {
                Imovel_Venda_Permuta_AluguerController ImovelCtrl = new Imovel_Venda_Permuta_AluguerController();
                Imovel_Venda_Permuta_Aluguer imovel = await ImovelCtrl.get(visita.ImovelId);
                string diaSemana = visita.Data.DayOfWeek.ToString();
                List<string> diasDaSemana = imovel.DiasSemana.Split(';').ToList();
                foreach (string dia in diasDaSemana)
                    if (dia == diaSemana && imovel.HoraAbertura <= Convert.ToInt32(visita.Hora.Hour.ToString())
                        && imovel.HoraFecho >= Convert.ToInt32(visita.Hora.Hour.ToString()))
                    {
                        var client = WebApiHttpClient.GetClient();
                        string pedidoVisitaJSON = JsonConvert.SerializeObject(visita);
                        HttpContent content = new StringContent(pedidoVisitaJSON,
                        System.Text.Encoding.Unicode, "application/json");
                        var response = await client.PutAsync("api/PedidoVisita/" + visita.PedidoVisitaId, content);

                        if (response.IsSuccessStatusCode)
                            return RedirectToAction("Index");
                        else
                            return RedirectToAction("UnAuthenticated", "Home");
                    }
                return Content("ERRO: O imóvel não se encontra disponivel na data ou hora escolhida.");
            }
            catch
            {
                return RedirectToAction("Erro", "Home");
            }
        }

        // GET: PedidoVisita/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/PedidoVisita/" + id);
            if (response.IsSuccessStatusCode)
            {

ClienteAPP/ClienteAPP/Views/PedidoVisita/Create.cshtml
@model ClienteAPP.Models.PedidoVisita

@{
    ViewBag.Title = "Create";
}

<h2>Create - Pedido de Visita</h2>

<div>
    <h4>Horário de visita do imóvel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Hora de abertura
        </dt>
        <dd>
            @ViewBag.imovel.HoraAbertura
        </dd>

        <dt>
            Hora de fecho
        </dt>
        <dd>
            @ViewBag.imovel.HoraFecho
        </dd>

        <dt>
            Dias da semana
        </dt>
        <dd>
            @ViewBag.imovel.DiasSemana
        </dd>

        <dt>
            Duração da visita
        </dt>
        <dd>
            @ViewBag.imovel.DuraçãoVisita
        </dd>

    </dl>
</div>

<br/>
<h4>Pedido de visita</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MediadorId)
        @Html.HiddenFor(model => model.ImovelId)

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>

    <div>
        @Html.ActionLink("Back to List", "Index", "Anuncios")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
}

ClienteAPP/ClienteAPP/Views/PedidoVisita/Delete.cshtml
@model ClienteAPP.Models.PedidoVisita

@{
    ViewBag.Title = "Delete";
}

<h2>Delete - Pedido de visita</h2>

<h3>Are you sure you want to delete this?</h3>

<div>
    <h4>Horário de visita do imóvel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Hora de abertura
        </dt>
        <dd>
            @ViewBag.imovel.HoraAbertura
        </dd>

        <dt>
            Hora de fecho
        </dt>
        <dd>
            @ViewBag.imovel.HoraFecho
        </dd>

        <dt>
            Dias da semana
        </dt>
        <dd>
            @ViewBag.imovel.DiasSemana
        </dd>

        <dt>
            Duração da visita
        </dt>
        <dd>
            @ViewBag.imovel.DuraçãoVisita
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Details", "Details", new { controller = "Imovel_Venda_Permuta_Aluguer", id = Model.ImovelId })
</p>

<br />
<h4>Pedido de visita</h4>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Data
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            Hora
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hora.TimeOfDay)
        </dd>

        <dt>
            Estado
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClienteAPP/ClienteAPP/Views/PedidoVisita/Details.cshtml
@model ClienteAPP.Models.PedidoVisita

@{
    ViewBag.Title = "Details";
}

<h2>Details - Pedido de visita</h2>

<div>
    <h4>Horário de visita do imóvel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Hora de abertura
        </dt>
        <dd>
            @ViewBag.imovel.HoraAbertura
        </dd>

        <dt>
            Hora de fecho
        </dt>
        <dd>
            @ViewBag.imovel.HoraFecho
        </dd>

        <dt>
            Dias da semana
        </dt>
        <dd>
            @ViewBag.imovel.DiasSemana
        </dd>

        <dt>
            Duração da visita
        </dt>
        <dd>
            @ViewBag.imovel.DuraçãoVisita
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Details", "Details", new { controller = "Imovel_Venda_Permuta_Aluguer", id = Model.ImovelId})
</p>

<br />
<h4>Pedido de visita</h4>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Data
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            Hora
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hora.TimeOfDay)
        </dd>

        <dt>
            Estado
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PedidoVisitaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClienteAPP/ClienteAPP/Views/PedidoVisita/Edit.cshtml
@model ClienteAPP.Models.PedidoVisita

@{
    ViewBag.Title = "Edit";
}

<h2>Edit - Pedido de visita</h2>

<div>
    <h4>Horário de visita do imóvel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Hora de abertura
        </dt>
        <dd>
            @ViewBag.imovel.HoraAbertura
        </dd>

        <dt>
            Hora de fecho
        </dt>
        <dd>
            @ViewBag.imovel.HoraFecho
        </dd>

        <dt>
            Dias da semana
        </dt>
        <dd>
            @ViewBag.imovel.DiasSemana
        </dd>

        <dt>
            Duração da visita
        </dt>
        <dd>
            @ViewBag.imovel.DuraçãoVisita
        </dd>

    </dl>
</div>

<br />
<h4>Pedido de visita</h4>

@using (Html.BeginForm("Edit", "PedidoVisita", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PedidoVisitaId)
        @Html.HiddenFor(model => model.ClienteId)
        @Html.HiddenFor(model => model.MediadorId)
        @Html.HiddenFor(model => model.ImovelId)
        @Html.HiddenFor(model => model.Estado)

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClienteAPP/ClienteAPP/Views/PedidoVisita/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index - Agenda</h2>

@if (@ViewBag.visitas.Count > 0)
{
    <table class="table">
        <tr>
            <th>
                Data
            </th>

            <th>
                Hora
            </th>

            <th>
                Estado
            </th>

            <th>
                Duração Visita
            </th>

            <th>
                Tipo de Imovel
            </th>

            <th>
                Local
            </th>

            <th>
                Latitude
            </th>

            <th>
                Longitude
            </th>

            <th></th>
        </tr>

        @for (var i = 0; i < ViewBag.visitas.Count; i++)
        {
            <tr>
                <td>
                    @ViewBag.visitas[i].Data.Day/@ViewBag.visitas[i].Data.Month/@ViewBag.visitas[i].Data.Year
                </td>

                <td>
                    @ViewBag.visitas[i].Hora.TimeOfDay
                </td>

                <td>
                    @ViewBag.visitas[i].Estado
                </td>

                <td>
                    @ViewBag.imoveis[i].DuraçãoVisita
                </td>

                <td>
                    @ViewBag.imoveis[i].tipoImovel
                </td>

                <td>
                    @ViewBag.imoveis[i].local
                </td>

                <td>
                    @ViewBag.imoveis[i].latitude
                </td>

                <td>
                    @ViewBag.imoveis[i].longitude
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = ViewBag.visitas[i].PedidoVisitaId }) |
                    @Html.ActionLink("Details", "Details", new { id = ViewBag.visitas[i].PedidoVisitaId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = ViewBag.visitas[i].PedidoVisitaId })
                </td>

            </tr>
        }
    </table>
}

else
{
    <br />
    <h5>Não existem pedidos de visita criados.</h5>
}