ClienteAPP/ClienteAPP/Controllers/RoleController.cs
using ClienteAPP.Helpers;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ClienteAPP.Controllers
{
    public class RoleController : Controller
    {
        // GET: Role
        public async Task<List<string>> Index()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Role/");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var roles = JsonConvert.DeserializeObject<IEnumerable<string>>(content);
                return roles.ToList();
            }
            else
                return null;
        }

        public async Task<List<string>> GetUserRoles(string UserId)
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Role/GetUserRoles/" + UserId);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var roles = JsonConvert.DeserializeObject<IEnumerable<string>>(content);
                return roles.ToList();
            }
            else
                return null;
        }

        public async Task<ActionResult> PromoverUser(string UserId)
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Role/PromoverUser/" + UserId);
            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index", "Users");
            else
                return RedirectToAction("Erro", "Home");
        }

        public async Task<ActionResult> DespromoverUser(string UserId)
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Role/DespromoverUser/" + UserId);
            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index", "Users");
            else
                return RedirectToAction("Erro", "Home");
        }
    }
}

ClienteAPP/ClienteAPP/Controllers/UsersController.cs
using ClienteAPP.Helpers;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ClienteAPP.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public async Task<ActionResult> Index()
        {
            if (WebApiHttpClient.getToken() == null)
                return RedirectToAction("UnAuthenticated", "Home");

            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Users/");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var getUsers = JsonConvert.DeserializeObject<IEnumerable<string>>(content);

                List<string> usersId = new List<string>();
                foreach (var user in getUsers)
                    usersId.Add(user);

                List<string> usersEmail = new List<string>();
                foreach (string Id in usersId)
                {
                    response = await client.GetAsync("api/Users/" + Id);
                    content = await response.Content.ReadAsStringAsync();
                    var email = JsonConvert.DeserializeObject<string>(content);
                    usersEmail.Add(email.ToString());
                }

                List<string> userRoles = new List<string>();
                RoleController role = new RoleController();
                foreach (var user in usersId)
                {
                    List<string> roles = await role.GetUserRoles(user);
                    foreach (string r in roles)
                        userRoles.Add(r);
                }

                ViewBag.usersId = usersId;
                ViewBag.usersEmail = usersEmail;
                ViewBag.userRoles = userRoles;

                return View();
            }
            else
                return null;
        }
    }
}

ClienteAPP/ClienteAPP/Views/Users/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index - Gerir utilizadores</h2>

<table class="table">
    <tr>
        <th>
            Email
        </th>

        <th>
            Role
        </th>

        <th></th>
    </tr>

@{
    var count = 0;
    foreach (string user in @ViewBag.usersId)
    {
        if (!@ViewBag.userRoles[count].Equals("Admin"))
        {
            <tr>
                <td>
                    @ViewBag.usersEmail[count]
                </td>
                <td>
                    @ViewBag.userRoles[count]
                </td>
                <td>
                    @if (@ViewBag.userRoles[count].Equals("Cliente"))
                    {
                        <a href="@Url.Action("PromoverUser", "Role", new { UserId = user })"
                            class="btn btn-primary btn-success"><span class="glyphicon glyphicon-circle-arrow-up"> 
                            Promover</span></a>
                    }
                    else
                    {
                        <a href="@Url.Action("DespromoverUser", "Role", new { UserId = user })"
                            class="btn btn-primary btn-danger"><span class="glyphicon glyphicon-circle-arrow-down"> 
                            Despromover</span></a>
                    }
                </td>
            </tr>
        }
        count++;
    }
}
</table>